# Analisi preliminare dataset Spesa Storica Comuni

Contiene i costi rilevati per i vari comuni usando: questionario, istat e altri sorgenti istituzionali

In [25]:
import pandas as pd
import numpy as np

# set the max number of columns to display
pd.options.display.max_columns = 98

In [2]:
! head -n 2 '../pac_sose/economia/spesa_comuni/spesa_storica_servizi/spesa_storica_servizi.csv.read'

"ANNO";"COMUNE_CAT_COD";"SPESA_CCC_FC01A";"TOT_SPESA_CCC_FC01A";"SPESA_CCC_FC01B";"TOT_SPESA_CCC_FC01B";"SPESA_CCC_FC01C";"TOT_SPESA_CCC_FC01C";"SPESA_CCC_FC01D";"TOT_SPESA_CCC_FC01D";"SPESA_CCC_FC02U";"TOT_SPESA_CCC_FC02U";"SPESA_CCC_FC03U";"TOT_SPESA_CCC_FC03U";"SPESA_CCC_FC04A";"TOT_SPESA_CCC_FC04A";"SPESA_CCC_FC04B";"TOT_SPESA_CCC_FC04B";"SPESA_CCC_FC05A";"TOT_SPESA_CCC_FC05A";"SPESA_CCC_FC05B";"TOT_SPESA_CCC_FC05B";"SPESA_CCC_FC06A";"TOT_SPESA_CCC_FC06A";"SPESA_CCC_FC06B";"TOT_SPESA_CCC_FC06B";"SPESA_CCC_tot";"TOT_SPESA_CCC_tot"
"2010";"A001";"128832.9";"497170185.24";"706678.7";"1024499937.3";"210454.3";"551023543";"2160820.2";"6386493525.4";"828153";"2641561106.1";"1249230";"3568619418";"735459";"2212809015";"0";"985882751.23";"945336";"1671883262";"3036962";"7605033852.3";"1913498.49";"4673165534.2";"478163";"1443110787";"12393587.59";"33261252916.76"

In [3]:
path_spesa_comuni = '../pac_sose/economia/spesa_comuni/spesa_storica_servizi/spesa_storica_servizi.csv.read'

In [4]:
df_spesa_comuni = pd.read_csv(path_spesa_comuni, sep=';')

In [5]:
df_spesa_comuni.shape

(26799, 28)

In [6]:
df_spesa_comuni.describe(include='all')

,ANNO,COMUNE_CAT_COD,SPESA_CCC_FC01A,TOT_SPESA_CCC_FC01A,SPESA_CCC_FC01B,TOT_SPESA_CCC_FC01B,SPESA_CCC_FC01C,TOT_SPESA_CCC_FC01C,SPESA_CCC_FC01D,TOT_SPESA_CCC_FC01D,...,SPESA_CCC_FC05A,TOT_SPESA_CCC_FC05A,SPESA_CCC_FC05B,TOT_SPESA_CCC_FC05B,SPESA_CCC_FC06A,TOT_SPESA_CCC_FC06A,SPESA_CCC_FC06B,TOT_SPESA_CCC_FC06B,SPESA_CCC_tot,TOT_SPESA_CCC_tot
count,26799.000000,26799,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,...,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,2.679900e+04,1.340100e+04,1.340100e+04
unique,NaN,6702,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,L756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2011.499832,NaN,8.577028e+04,5.746527e+08,1.541447e+05,1.032795e+09,8.644842e+04,5.792487e+08,8.917068e+05,5.974560e+09,...,2.552693e+05,1.710341e+09,1.232597e+06,8.258333e+09,7.130245e+05,4.777242e+09,1.727580e+05,1.157473e+09,5.013244e+06,3.359229e+10
std,1.118105,NaN,6.757747e+05,1.169119e+08,1.160821e+06,3.853813e+07,5.706915e+05,3.289653e+07,8.127964e+06,5.466493e+08,...,2.421434e+06,4.230690e+07,1.140452e+07,4.444083e+08,6.629166e+06,1.060130e+08,3.623444e+06,1.698065e+08,5.107025e+07,3.311270e+08
min,2010.000000,NaN,0.000000e+00,4.971702e+08,0.000000e+00,9.892256e+08,0.000000e+00,5.429716e+08,0.000000e+00,5.033531e+09,...,0.000000e+00,1.671883e+09,0.000000e+00,7.605034e+09,0.000000e+00,4.673166e+09,-1.029772e+07,1.001484e+09,7.159360e+02,3.326125e+10
25%,2010.000000,NaN,3.017332e+03,4.971702e+08,3.254803e+04,1.022473e+09,2.059783e+04,5.510235e+08,1.643562e+05,6.228627e+09,...,7.000000e+03,1.671883e+09,1.199990e+05,7.605034e+09,3.116500e+04,4.673166e+09,0.000000e+00,1.070603e+09,6.135613e+05,3.326125e+10
50%,2011.000000,NaN,2.244340e+04,5.072225e+08,7.223867e+04,1.024500e+09,3.893408e+04,5.510235e+08,2.981398e+05,6.249405e+09,...,3.287166e+04,1.678297e+09,2.867830e+05,8.097245e+09,1.091644e+05,4.728718e+09,0.000000e+00,1.114565e+09,1.318474e+06,3.326125e+10
75%,2012.000000,NaN,6.363805e+04,5.174737e+08,1.408708e+05,1.024500e+09,7.152880e+04,6.032929e+08,6.137037e+05,6.386494e+09,...,1.267183e+05,1.712683e+09,7.534057e+05,8.614381e+09,3.823620e+05,4.753275e+09,1.500000e+04,1.443111e+09,3.126427e+06,3.392348e+10
max,2013.000000,NaN,5.374296e+07,7.767792e+08,9.638855e+07,1.094984e+09,4.584875e+07,6.197194e+08,6.983870e+08,6.386494e+09,...,1.843937e+08,1.778518e+09,1.017224e+09,8.716966e+09,4.187557e+08,4.953856e+09,3.065708e+08,1.443111e+09,3.784947e+09,3.392348e+10

## Columns

Contengono le voci di spesa dichiarate dai comuni in base ai questionari per l'anno 2010 e 2013.

In [7]:
columns = [c for c in df_spesa_comuni.columns if not c.startswith("TOT")]
columns

['ANNO',
 'COMUNE_CAT_COD',
 'SPESA_CCC_FC01A',
 'SPESA_CCC_FC01B',
 'SPESA_CCC_FC01C',
 'SPESA_CCC_FC01D',
 'SPESA_CCC_FC02U',
 'SPESA_CCC_FC03U',
 'SPESA_CCC_FC04A',
 'SPESA_CCC_FC04B',
 'SPESA_CCC_FC05A',
 'SPESA_CCC_FC05B',
 'SPESA_CCC_FC06A',
 'SPESA_CCC_FC06B',
 'SPESA_CCC_tot']

- ANNO
- COMUNE_CAT_COD: codice comune
- SPESA_CCC_FC01A: entrate tributarie
- SPESA_CCC_FC01B: ufficio tecnico
- SPESA_CCC_FC01C: anagrafe, stato civile, leva e servizio statistico
- SPESA_CCC_FC01D: altri servizi generali
- SPESA_CCC_FC02U: polizia locale
- SPESA_CCC_FC03U: istruzione pubblica
- SPESA_CCC_FC04A: viabilita'
- SPESA_CCC_FC04B: trasporto pubblico e servizi connessi
- SPESA_CCC_FC05A: gestione del territorio
- SPESA_CCC_FC05B: ambiente
- SPESA_CCC_FC06A: settore sociale
- SPESA_CCC_FC06B: asili nido

Each column as a TOTAL_SPESA_CCC_XXXXX that represent the total expense at Italian Level

a detailed description can be found [here](https://github.com/altroisi/daf-dataset-doc/tree/master/pac_sose)

## Add Column with the City Name

In [8]:
path_comuni = '../pac_agenziaentrate/regioni_citta/comuni/archivio_comuni/ElencoComuniAttuali_20170918.csv.read'

In [9]:
df_comuni = pd.read_csv(path_comuni, sep=';')

In [10]:
df_comuni.head()

,Codice Nazionale,Sigla Provincia,Denominazione Italiana,Denominazione Estera,Codice Catastale,Ufficio Catasto Terreni,Ufficio Catasto Fabbricati,Codice Conservatoria,Codice Istat,Data Costituzione,Attesa VCT Territorio,Attesa VCT Fabbricati
0,A001,PD,ABANO TERME,NaN,D3AB,PD,PD,PD00,28001.0,NaN,NaN,NaN
1,A004,LO,ABBADIA CERRETO,NaN,C1AB,LO,LO,LO00,98001.0,NaN,NaN,NaN
2,A005,LC,ABBADIA LARIANA,NaN,C4AC,LC,LC,LC00,97001.0,NaN,NaN,NaN
3,A006,SI,ABBADIA SAN SALVATORE,NaN,I9AB,SI,SI,SI10,52001.0,NaN,NaN,NaN
4,A007,OR,ABBASANTA,NaN,V4AB,OR,OR,OR00,95001.0,NaN,NaN,NaN

In [11]:
df_comuni.describe(include='all')

,Codice Nazionale,Sigla Provincia,Denominazione Italiana,Denominazione Estera,Codice Catastale,Ufficio Catasto Terreni,Ufficio Catasto Fabbricati,Codice Conservatoria,Codice Istat,Data Costituzione,Attesa VCT Territorio,Attesa VCT Fabbricati
count,7978,7886,7978,117,7944,7580,7587,7635,7976.000000,55,26,20
unique,7978,109,7971,117,7944,100,100,138,NaN,11,1,1
top,M325,TO,VALVERDE,JENESIEN,D7CK,TO,TO,BG00,NaN,01/01/2016,SI,SI
freq,1,316,2,1,1,315,315,251,NaN,25,26,20
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45003.384403,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32478.410356,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1001.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16143.750000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40002.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,72043.250000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110010.000000,NaN,NaN,NaN

## Merge dei Dati

In [12]:
df_spese_comuni_merge = pd.merge(
    df_spesa_comuni, 
    df_comuni, 
    how='left',
    right_on='Codice Nazionale', 
    left_on='COMUNE_CAT_COD')
df_spese_comuni_merge.shape

(26799, 40)

In [13]:
df_spese_comuni_merge.head()

,ANNO,COMUNE_CAT_COD,SPESA_CCC_FC01A,TOT_SPESA_CCC_FC01A,SPESA_CCC_FC01B,TOT_SPESA_CCC_FC01B,SPESA_CCC_FC01C,TOT_SPESA_CCC_FC01C,SPESA_CCC_FC01D,TOT_SPESA_CCC_FC01D,...,Denominazione Italiana,Denominazione Estera,Codice Catastale,Ufficio Catasto Terreni,Ufficio Catasto Fabbricati,Codice Conservatoria,Codice Istat,Data Costituzione,Attesa VCT Territorio,Attesa VCT Fabbricati
0,2010,A001,128832.900000,4.971702e+08,706678.700000,1.024500e+09,210454.3,551023543.0,2160820.2,6.386494e+09,...,ABANO TERME,NaN,D3AB,PD,PD,PD00,28001.0,NaN,NaN,NaN
1,2010,A004,48.290741,4.971702e+08,3022.240741,1.024500e+09,54.6,551023543.0,110355.7,6.386494e+09,...,ABBADIA CERRETO,NaN,C1AB,LO,LO,LO00,98001.0,NaN,NaN,NaN
2,2010,A005,50458.800000,4.971702e+08,143147.200000,1.024500e+09,59466.4,551023543.0,359500.4,6.386494e+09,...,ABBADIA LARIANA,NaN,C4AC,LC,LC,LC00,97001.0,NaN,NaN,NaN
3,2010,A006,34853.700000,4.971702e+08,127310.400000,1.024500e+09,61798.8,551023543.0,720716.5,6.386494e+09,...,ABBADIA SAN SALVATORE,NaN,I9AB,SI,SI,SI10,52001.0,NaN,NaN,NaN
4,2010,A008,13393.100000,4.971702e+08,2100.000000,1.024500e+09,20444.9,551023543.0,92740.9,6.386494e+09,...,ABBATEGGIO,NaN,N3AB,PE,PE,PE00,68001.0,NaN,NaN,NaN

In [14]:
df_spese_comuni_merge.ANNO.value_counts()

2010    6702
2013    6699
2012    6699
2011    6699
Name: ANNO, dtype: int64

## Merge Dati con [DatiIRPEF](http://localhost:8888/notebooks/mise_aiuti/DAF_MEF_DatiIRPEF.ipynb)

In [15]:
df_irpef_comuni = pd.read_csv('../mise_aiuti/data/redditi_irpef.csv')
df_irpef_comuni = df_irpef_comuni.drop(df_irpef_comuni.columns[0], axis=1)

In [20]:
df_irpef_comuni.columns

Index(['Addizionale comunale dovuta - Ammontare',
       'Addizionale comunale dovuta - Frequenza',
       'Addizionale regionale dovuta - Ammontare',
       'Addizionale regionale dovuta - Frequenza', 'Anno di imposta',
       'Codice Istat', 'Codice Istat Comune', 'Codice Istat Regione',
       'Codice catastale', 'Denominazione Comune', 'Imposta netta - Ammontare',
       'Imposta netta - Frequenza', 'Numero contribuenti',
       'Reddito complessivo da 0 a 10000 euro - Ammontare',
       'Reddito complessivo da 0 a 10000 euro - Frequenza',
       'Reddito complessivo da 10000 a 15000 euro - Ammontare',
       'Reddito complessivo da 10000 a 15000 euro - Frequenza',
       'Reddito complessivo da 15000 a 26000 euro - Ammontare',
       'Reddito complessivo da 15000 a 26000 euro - Frequenza',
       'Reddito complessivo da 26000 a 55000 euro - Ammontare',
       'Reddito complessivo da 26000 a 55000 euro - Frequenza',
       'Reddito complessivo da 55000 a 75000 euro - Ammontare',
       'Reddito complessivo da 55000 a 75000 euro - Frequenza',
       'Reddito complessivo da 75000 a 120000 euro - Ammontare',
       'Reddito complessivo da 75000 a 120000 euro - Frequenza',
       'Reddito complessivo minore di zero euro - Ammontare',
       'Reddito complessivo minore di zero euro - Frequenza',
       'Reddito complessivo minore o uguale a zero euro - Ammontare',
       'Reddito complessivo minore o uguale a zero euro - Frequenza',
       'Reddito complessivo oltre 120000 euro - Ammontare',
       'Reddito complessivo oltre 120000 euro - Frequenza',
       'Reddito da fabbricati - Ammontare',
       'Reddito da fabbricati - Frequenza',
       'Reddito da lavoro autonomo (comprensivo dei valori nulli) - Ammontare',
       'Reddito da lavoro autonomo (comprensivo dei valori nulli) - Frequenza',
       'Reddito da lavoro autonomo (compresi nulli) - Ammontare',
       'Reddito da lavoro autonomo (compresi nulli) - Frequenza',
       'Reddito da lavoro dipendente e assimilati - Ammontare',
       'Reddito da lavoro dipendente e assimilati - Frequenza',
       'Reddito da partecipazione  (comprensivo dei valori nulli) - Ammontare',
       'Reddito da partecipazione  (comprensivo dei valori nulli) - Frequenza',
       'Reddito da partecipazione  (compresi nulli) - Frequenza',
       'Reddito da partecipazione (compresi nulli) - Ammontare',
       'Reddito da pensione - Ammontare', 'Reddito da pensione - Frequenza',
       'Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Ammontare',
       'Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Frequenza',
       'Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Ammontare',
       'Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Frequenza',
       'Reddito imponibile - Ammontare', 'Reddito imponibile - Frequenza',
       'Reddito imponibile addizionale - Ammontare',
       'Reddito imponibile addizionale - Frequenza',
       'Reddito imponibile addizionale IRPEF - Ammontare',
       'Reddito imponibile addizionale IRPEF - Frequenza',
       'Reddito spettanza imprenditore ordinaria  (compresi nulli) - Ammontare',
       'Reddito spettanza imprenditore ordinaria  (compresi nulli) - Frequenza',
       'Reddito spettanza imprenditore semplificata (compresi nulli) - Ammontare',
       'Reddito spettanza imprenditore semplificata (compresi nulli) - Frequenza',
       'Regione', 'Sigla Provincia'],
      dtype='object')

I dati relativi all'irpef coprono il periodo 2009-2015. Mentre quelli sulle spese di open sose vanno dal 2010 al 2013

In [16]:
df_irpef_comuni['Anno di imposta'].value_counts()

2009    8095
2011    8093
2010    8093
2012    8073
2013    8059
2014    8049
2015    8000
Name: Anno di imposta, dtype: int64

In [17]:
df_spese_comuni_merge['ANNO'].value_counts()

2010    6702
2013    6699
2012    6699
2011    6699
Name: ANNO, dtype: int64

In [18]:
print('shape irpef comuni ',df_irpef_comuni.shape)
print('shape spese comuni', df_spese_comuni_merge.shape)

shape irpef comuni  (56462, 61)
shape spese comuni (26799, 40)

We restrict the analysis on data in the period 2010-2013. Thus, we join the data from the two datasets based on cod_comune and year

In [22]:
df_spese_comuni_irpef = pd.merge(
    df_spese_comuni_merge, 
    df_irpef_comuni, 
    how='left',
    left_on=['COMUNE_CAT_COD', 'ANNO'], 
    right_on=['Codice catastale', 'Anno di imposta'])
df_spese_comuni_irpef.shape

(26799, 101)

In [42]:
df_spese_comuni_irpef['ANNO'].value_counts()

2010    6702
2013    6699
2012    6699
2011    6699
Name: ANNO, dtype: int64

In [43]:
df_spese_comuni_irpef.head()

,ANNO,COMUNE_CAT_COD,SPESA_CCC_FC01A,TOT_SPESA_CCC_FC01A,SPESA_CCC_FC01B,TOT_SPESA_CCC_FC01B,SPESA_CCC_FC01C,TOT_SPESA_CCC_FC01C,SPESA_CCC_FC01D,TOT_SPESA_CCC_FC01D,SPESA_CCC_FC02U,TOT_SPESA_CCC_FC02U,SPESA_CCC_FC03U,TOT_SPESA_CCC_FC03U,SPESA_CCC_FC04A,TOT_SPESA_CCC_FC04A,SPESA_CCC_FC04B,TOT_SPESA_CCC_FC04B,SPESA_CCC_FC05A,TOT_SPESA_CCC_FC05A,SPESA_CCC_FC05B,TOT_SPESA_CCC_FC05B,SPESA_CCC_FC06A,TOT_SPESA_CCC_FC06A,SPESA_CCC_FC06B,TOT_SPESA_CCC_FC06B,SPESA_CCC_tot,TOT_SPESA_CCC_tot,Codice Nazionale,Sigla Provincia_x,Denominazione Italiana,Denominazione Estera,Codice Catastale,Ufficio Catasto Terreni,Ufficio Catasto Fabbricati,Codice Conservatoria,Codice Istat_x,Data Costituzione,Attesa VCT Territorio,Attesa VCT Fabbricati,Addizionale comunale dovuta - Ammontare,Addizionale comunale dovuta - Frequenza,Addizionale regionale dovuta - Ammontare,Addizionale regionale dovuta - Frequenza,Anno di imposta,Codice Istat_y,Codice Istat Comune,Codice Istat Regione,Codice catastale,...,Numero contribuenti,Reddito complessivo da 0 a 10000 euro - Ammontare,Reddito complessivo da 0 a 10000 euro - Frequenza,Reddito complessivo da 10000 a 15000 euro - Ammontare,Reddito complessivo da 10000 a 15000 euro - Frequenza,Reddito complessivo da 15000 a 26000 euro - Ammontare,Reddito complessivo da 15000 a 26000 euro - Frequenza,Reddito complessivo da 26000 a 55000 euro - Ammontare,Reddito complessivo da 26000 a 55000 euro - Frequenza,Reddito complessivo da 55000 a 75000 euro - Ammontare,Reddito complessivo da 55000 a 75000 euro - Frequenza,Reddito complessivo da 75000 a 120000 euro - Ammontare,Reddito complessivo da 75000 a 120000 euro - Frequenza,Reddito complessivo minore di zero euro - Ammontare,Reddito complessivo minore di zero euro - Frequenza,Reddito complessivo minore o uguale a zero euro - Ammontare,Reddito complessivo minore o uguale a zero euro - Frequenza,Reddito complessivo oltre 120000 euro - Ammontare,Reddito complessivo oltre 120000 euro - Frequenza,Reddito da fabbricati - Ammontare,Reddito da fabbricati - Frequenza,Reddito da lavoro autonomo (comprensivo dei valori nulli) - Ammontare,Reddito da lavoro autonomo (comprensivo dei valori nulli) - Frequenza,Reddito da lavoro autonomo (compresi nulli) - Ammontare,Reddito da lavoro autonomo (compresi nulli) - Frequenza,Reddito da lavoro dipendente e assimilati - Ammontare,Reddito da lavoro dipendente e assimilati - Frequenza,Reddito da partecipazione (comprensivo dei valori nulli) - Ammontare,Reddito da partecipazione (comprensivo dei valori nulli) - Frequenza,Reddito da partecipazione (compresi nulli) - Frequenza,Reddito da partecipazione (compresi nulli) - Ammontare,Reddito da pensione - Ammontare,Reddito da pensione - Frequenza,Reddito di spettanza dell'imprenditore in contabilita' ordinaria (comprensivo dei valori nulli) - Ammontare,Reddito di spettanza dell'imprenditore in contabilita' ordinaria (comprensivo dei valori nulli) - Frequenza,Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Ammontare,Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Frequenza,Reddito imponibile - Ammontare,Reddito imponibile - Frequenza,Reddito imponibile addizionale - Ammontare,Reddito imponibile addizionale - Frequenza,Reddito imponibile addizionale IRPEF - Ammontare,Reddito imponibile addizionale IRPEF - Frequenza,Reddito spettanza imprenditore ordinaria (compresi nulli) - Ammontare,Reddito spettanza imprenditore ordinaria (compresi nulli) - Frequenza,Reddito spettanza imprenditore semplificata (compresi nulli) - Ammontare,Reddito spettanza imprenditore semplificata (compresi nulli) - Frequenza,Regione,Sigla Provincia_y
0,2010,A001,128832.900000,4.971702e+08,706678.700000,1.024500e+09,210454.3,551023543.0,2160820.2,6.386494e+09,828153.000000,2.641561e+09,1.249230e+06,3.568619e+09,735459.00000,2.212809e+09,0.0,9.858828e+08,945336.000000,1.671883e+09,3.036962e+06,7.605034e+09,1.913498e+06,4.673166e+09,478163.0,1.443111e+09,1.239359e+07,3.326125e+10,A001,PD,ABANO TERME,NaN,D3AB,PD,PD,PD00,28001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.0,28001.0,NaN,NaN,A001,...,NaN,17976401.0,3629.0,26012549.0,2063.0,96948784.0,4885.0,90207515.0,2572.0,25551207.0,400.0,29095063.0,313.0,NaN,NaN,-760040.0,82.0,30132780.0,158.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,288473057.0,11377.0,NaN,NaN,NaN,NaN,VENETO,PD
1,2010,A004,48.290741,4.971702e+08,3022.240741,1.024500e+09,54.6,551023543.0,110355.7,6.386494e+09,5867.751323,2.641561e+09,1.427755e+04,3.568619e+09,9812.86455,2.212809e+09,0.0,9.858828e+08,2568.000000,1.671883e+09,2.534683e+04,7.605034e+09,1.195843e+04,4.673166e+09,0.0,1.443111e+09,1.833123e+05,3.326125e+10,A004,LO,ABBADIA CERRETO,NaN,C1AB,LO,LO,LO00,98001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.0,98001.0,NaN,NaN,A004,...,NaN,312411.0,56.0,608689.0,47.0,1482927.0,75.0,960638.0,29.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3396780.0,170.0,NaN,NaN,NaN,NaN,LOMBARDIA,LO
2,2010,A005,50458.800000,4.971702e+08,143147.200000,1.024500e+09,59466.4,551023543.0,359500.4,6.386494e+09,158712.000000,2.641561e+09,3.325228e+05,3.568619e+09,202733.86636,2.212809e+09,2960.0,9.858828e+08,21451.000000,1.671883e+09,2.774860e+05,7.605034e+09,3.028070e+05,4.673166e+09,0.0,1.443111e+09,1.911245e+06,3.326125e+10,A005,LC,ABBADIA LARIANA,NaN,C4AC,LC,LC,LC00,97001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.0,97001.0,NaN,NaN,A005,...,NaN,2919974.0,549.0,4024492.0,319.0,19467952.0,967.0,16094112.0,474.0,3969550.0,63.0,3756520.0,39.0,NaN,NaN,-26823.0,7.0,3869133.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49890297.0,2035.0,NaN,NaN,NaN,NaN,LOMBARDIA,LC
3,2010,A006,34853.700000,4.971702e+08,127310.400000,1.024500e+09,61798.8,551023543.0,720716.5,6.386494e+09,266539.000000,2.641561e+09,3.199990e+05,3.568619e+09,369236.00000,2.212809e+09,71988.0,9.858828e+08,367137.353427,1.671883e+09,1.450484e+06,7.605034e+09,4.138070e+05,4.673166e+09,0.0,1.443111e+09,4.203870e+06,3.326125e+10,A006,SI,ABBADIA SAN SALVATORE,NaN,I9AB,SI,SI,SI10,52001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.0,52001.0,NaN,NaN,A006,...,NaN,7888467.0,1643.0,12195657.0,977.0,33267055.0,1723.0,22647928.0,666.0,3268400.0,52.0,3250730.0,37.0,NaN,NaN,-464320.0,25.0,2084857.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,75677837.0,4044.0,NaN,NaN,NaN,NaN,TOSCANA,SI
4,2010,A008,13393.100000,4.971702e+08,2100.000000,1.024500e+09,20444.9,551023543.0,92740.9,6.386494e+09,0.000000,2.641561e+09,4.827000e+04,3.568619e+09,28379.00000,2.212809e+09,0.0,9.858828e+08,66556.000000,1.671883e+09,4.800000e+04,7.605034e+09,1.310100e+04,4.673166e+09,0.0,1.443111e+09,3.329849e+05,3.326125e+10,A008,PE,ABBATEGGIO,NaN,N3AB,PE,PE,PE00,68001.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.0,68001.0,NaN,NaN,A008,...,NaN,734074.0,192.0,605620.0,49.0,1540693.0,78.0,831685.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,-15059.0,7.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3194389.0,189.0,NaN,NaN,NaN,NaN,ABRUZZO,PE

In [44]:
df_final = df_spese_comuni_irpef

In [45]:
is_null = df_final.isnull().all() / len(df_final)
is_null[is_null > 0.0]

Denominazione Estera                                   0.000037
Reddito complessivo minore di zero euro - Ammontare    0.000037
Reddito complessivo minore di zero euro - Frequenza    0.000037
dtype: float64

### Check the availale columns

Possiamo raggruppare le colonne in:
1. dati demografici: 
    -  COMUNE_CAT_COD
    -  Codice Catastale
    -  Codice Conservatoria
    -  Codice Istat Comune
    -  Codice Istat Regione
    -  Codice Istat_x
    -  Codice Istat_y
    -  Data Costituzione
    -  Denominazione Comune
    -  Denominazione Estera
    -  Denominazione Italiana
    -  Regione
    -  Sigla Provincia_x
    -  Sigla Provincia_y
    -  Ufficio Catasto Fabbricati
    -  Ufficio Catasto Terreni
   
   
2. dati sui redditi da lavoro per scaglione sotto forma di ammontare totale e frequenza
3. dettagli sui totali di reddito per voce (lavoro autonomo, fabbricati, partecipazione, pensione, imprenditoriale
4. spese totali per le voci:
    - COMUNE_CAT_COD: codice comune
    - SPESA_CCC_FC01A: entrate tributarie
    - SPESA_CCC_FC01B: ufficio tecnico
    - SPESA_CCC_FC01C: anagrafe, stato civile, leva e servizio statistico
    - SPESA_CCC_FC01D: altri servizi generali
    - SPESA_CCC_FC02U: polizia locale
    - SPESA_CCC_FC03U: istruzione pubblica
    - SPESA_CCC_FC04A: viabilita'
    - SPESA_CCC_FC04B: trasporto pubblico e servizi connessi
    - SPESA_CCC_FC05A: gestione del territorio
    - SPESA_CCC_FC05B: ambiente
    - SPESA_CCC_FC06A: settore sociale
    - SPESA_CCC_FC06B: asili nido
5. anno di riferimento
6. numero totale dei contribuenti

Di seguito il dettaglio con le colonne.

In [50]:
for c in sorted(df_final.columns.values):
    print('- ', c)

-  ANNO
-  Addizionale comunale dovuta - Ammontare
-  Addizionale comunale dovuta - Frequenza
-  Addizionale regionale dovuta - Ammontare
-  Addizionale regionale dovuta - Frequenza
-  Anno di imposta
-  Attesa VCT Fabbricati
-  Attesa VCT Territorio
-  COMUNE_CAT_COD
-  Codice Catastale
-  Codice Conservatoria
-  Codice Istat Comune
-  Codice Istat Regione
-  Codice Istat_x
-  Codice Istat_y
-  Codice Nazionale
-  Codice catastale
-  Data Costituzione
-  Denominazione Comune
-  Denominazione Estera
-  Denominazione Italiana
-  Imposta netta - Ammontare
-  Imposta netta - Frequenza
-  Numero contribuenti
-  Reddito complessivo da 0 a 10000 euro - Ammontare
-  Reddito complessivo da 0 a 10000 euro - Frequenza
-  Reddito complessivo da 10000 a 15000 euro - Ammontare
-  Reddito complessivo da 10000 a 15000 euro - Frequenza
-  Reddito complessivo da 15000 a 26000 euro - Ammontare
-  Reddito complessivo da 15000 a 26000 euro - Frequenza
-  Reddito complessivo da 26000 a 55000 euro - Ammontare
-  Reddito complessivo da 26000 a 55000 euro - Frequenza
-  Reddito complessivo da 55000 a 75000 euro - Ammontare
-  Reddito complessivo da 55000 a 75000 euro - Frequenza
-  Reddito complessivo da 75000 a 120000 euro - Ammontare
-  Reddito complessivo da 75000 a 120000 euro - Frequenza
-  Reddito complessivo minore di zero euro - Ammontare
-  Reddito complessivo minore di zero euro - Frequenza
-  Reddito complessivo minore o uguale a zero euro - Ammontare
-  Reddito complessivo minore o uguale a zero euro - Frequenza
-  Reddito complessivo oltre 120000 euro - Ammontare
-  Reddito complessivo oltre 120000 euro - Frequenza
-  Reddito da fabbricati - Ammontare
-  Reddito da fabbricati - Frequenza
-  Reddito da lavoro autonomo (comprensivo dei valori nulli) - Ammontare
-  Reddito da lavoro autonomo (comprensivo dei valori nulli) - Frequenza
-  Reddito da lavoro autonomo (compresi nulli) - Ammontare
-  Reddito da lavoro autonomo (compresi nulli) - Frequenza
-  Reddito da lavoro dipendente e assimilati - Ammontare
-  Reddito da lavoro dipendente e assimilati - Frequenza
-  Reddito da partecipazione  (comprensivo dei valori nulli) - Ammontare
-  Reddito da partecipazione  (comprensivo dei valori nulli) - Frequenza
-  Reddito da partecipazione  (compresi nulli) - Frequenza
-  Reddito da partecipazione (compresi nulli) - Ammontare
-  Reddito da pensione - Ammontare
-  Reddito da pensione - Frequenza
-  Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Ammontare
-  Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Frequenza
-  Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Ammontare
-  Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Frequenza
-  Reddito imponibile - Ammontare
-  Reddito imponibile - Frequenza
-  Reddito imponibile addizionale - Ammontare
-  Reddito imponibile addizionale - Frequenza
-  Reddito imponibile addizionale IRPEF - Ammontare
-  Reddito imponibile addizionale IRPEF - Frequenza
-  Reddito spettanza imprenditore ordinaria  (compresi nulli) - Ammontare
-  Reddito spettanza imprenditore ordinaria  (compresi nulli) - Frequenza
-  Reddito spettanza imprenditore semplificata (compresi nulli) - Ammontare
-  Reddito spettanza imprenditore semplificata (compresi nulli) - Frequenza
-  Regione
-  SPESA_CCC_FC01A
-  SPESA_CCC_FC01B
-  SPESA_CCC_FC01C
-  SPESA_CCC_FC01D
-  SPESA_CCC_FC02U
-  SPESA_CCC_FC03U
-  SPESA_CCC_FC04A
-  SPESA_CCC_FC04B
-  SPESA_CCC_FC05A
-  SPESA_CCC_FC05B
-  SPESA_CCC_FC06A
-  SPESA_CCC_FC06B
-  SPESA_CCC_tot
-  Sigla Provincia_x
-  Sigla Provincia_y
-  TOT_SPESA_CCC_FC01A
-  TOT_SPESA_CCC_FC01B
-  TOT_SPESA_CCC_FC01C
-  TOT_SPESA_CCC_FC01D
-  TOT_SPESA_CCC_FC02U
-  TOT_SPESA_CCC_FC03U
-  TOT_SPESA_CCC_FC04A
-  TOT_SPESA_CCC_FC04B
-  TOT_SPESA_CCC_FC05A
-  TOT_SPESA_CCC_FC05B
-  TOT_SPESA_CCC_FC06A
-  TOT_SPESA_CCC_FC06B
-  TOT_SPESA_CCC_tot
-  Ufficio Catasto Fabbricati
-  Ufficio Catasto Terreni

Dettaglio su nome e codici per i comuni

In [51]:
df_final[['Denominazione Comune', 
          'COMUNE_CAT_COD', 
          'Codice Catastale', 
          'Codice Conservatoria',
          'Codice Istat Comune',
          'Codice Istat Regione',
          'Codice Istat_x',
          'Codice Istat_y']].tail()

,Denominazione Comune,COMUNE_CAT_COD,Codice Catastale,Codice Conservatoria,Codice Istat Comune,Codice Istat Regione,Codice Istat_x,Codice Istat_y
26794,MONTIGLIO MONFERRATO,M302,A3FA,AL20,5121.0,1.0,5121.0,NaN
26795,MOSSO,M304,A6HW,BI00,96084.0,1.0,96084.0,NaN
26796,CAVALLINO-TREPORTI,M308,D1CB,VE00,27044.0,5.0,27044.0,NaN
26797,FONTE NUOVA,M309,M1GE,RM20,58122.0,12.0,58122.0,NaN
26798,LONATO DEL GARDA,M312,C3MS,BS00,17092.0,3.0,17092.0,NaN

## Add Total Population that pay taxes

filter the columns referring to the frequency of the people that pay taxes in the city. The sum of these values represent the total number of city citizens.

In [52]:
frequency_cols = [
 'Reddito complessivo da 0 a 10000 euro - Frequenza',
 'Reddito complessivo da 10000 a 15000 euro - Frequenza',
 'Reddito complessivo da 15000 a 26000 euro - Frequenza',
 'Reddito complessivo da 26000 a 55000 euro - Frequenza',
 'Reddito complessivo da 55000 a 75000 euro - Frequenza',
 'Reddito complessivo da 75000 a 120000 euro - Frequenza',
 'Reddito complessivo minore o uguale a zero euro - Frequenza',
 'Reddito complessivo oltre 120000 euro - Frequenza',
]

In [53]:
tot_citizens = df_final[frequency_cols].sum(axis=1)

In [54]:
if 'tot_contribuenti' in df_final.columns:
    df_final= df_final.drop('tot_contribuenti', axis=1)

In [55]:
df_final.insert(df_final.shape[1], 'tot_contribuenti', tot_citizens)

Check the results

In [56]:
df_br = df_final[(df_final['Sigla Provincia_y'] == 'RM')]
df_br = df_br.dropna(axis=1, how='all')

In [58]:
df_br[['Denominazione Comune', 'ANNO', 'tot_contribuenti', 'Numero contribuenti']][df_br['Denominazione Comune'] == 'ROMA']

      Denominazione Comune  ANNO  tot_contribuenti  Numero contribuenti
4990                  ROMA  2010         1904199.0                  NaN
11689                 ROMA  2011         1872905.0                  NaN
18388                 ROMA  2012         1885881.0            1947796.0
25087                 ROMA  2013         1886336.0            1936483.0

### Columns Cleanup

In [59]:
to_drop = [
    'Attesa VCT Fabbricati', 
    'Attesa VCT Territorio',
    'Data Costituzione',
    'Denominazione Estera',
]


to_merge = [
    [
        "Reddito da lavoro autonomo (comprensivo dei valori nulli) - Ammontare", 
        "Reddito da lavoro autonomo (compresi nulli) - Ammontare"
    ],
    [
        "Reddito da lavoro autonomo (comprensivo dei valori nulli) - Frequenza",
        "Reddito da lavoro autonomo (compresi nulli) - Frequenza"
    ],
    [
        "Reddito da partecipazione  (comprensivo dei valori nulli) - Ammontare", 
        "Reddito da partecipazione (compresi nulli) - Ammontare"
    ],
    [
        "Reddito da partecipazione  (comprensivo dei valori nulli) - Frequenza", 
        "Reddito da partecipazione  (compresi nulli) - Frequenza"
    ],
    [
        "Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Ammontare",
        "Reddito spettanza imprenditore ordinaria  (compresi nulli) - Ammontare"
    ],
    [
        "Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Frequenza",
        "Reddito spettanza imprenditore ordinaria  (compresi nulli) - Frequenza"
    ],
    [
        "Reddito spettanza imprenditore semplificata (compresi nulli) - Ammontare",
        "Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Ammontare"
    ],
    [
        "Reddito spettanza imprenditore semplificata (compresi nulli) - Frequenza",
        "Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Frequenza"
    ],
    [
        'Sigla Provincia_x', 
        'Sigla Provincia_y'
    ],
    [
        'Codice Istat_x',
        'Codice Istat_y'
    ],
    
]

to_merge_name = [
    'Reddito lavoro autonomo Ammontare',
    'Reddito lavoro autonomo Frequenza',
    'Reddito da partecipazione Ammontare',
    'Reddito da partecipazione Frequenza',    
    'Reddito imprenditore ordinario Ammontare',
    'Reddito imprenditore ordinario Frequenza',
    'Reddito imprenditore semplificata Ammontare',
    'Reddito imprenditore semplificata Frequenza',
    'Provincia',
    'Cod Istat'
]

In [62]:
import math
def merge_columns_data(row):
    a, b = row.values
    if type(a) is str:
        return a
    elif type(b) is str:
        return b
    elif math.isnan(a) and math.isnan(b):
        return a
    elif math.isnan(a):
        return b
    else:
        return a

In [63]:
for i in range(len(to_merge)):
    cols = to_merge[i]
    name = to_merge_name[i]
    df_final[name] = df_final[cols].apply(merge_columns_data,axis=1)

In [65]:
merged_to_drop = [val for sublist in to_merge for val in sublist] + to_drop
merged_to_drop

['Reddito da lavoro autonomo (comprensivo dei valori nulli) - Ammontare',
 'Reddito da lavoro autonomo (compresi nulli) - Ammontare',
 'Reddito da lavoro autonomo (comprensivo dei valori nulli) - Frequenza',
 'Reddito da lavoro autonomo (compresi nulli) - Frequenza',
 'Reddito da partecipazione  (comprensivo dei valori nulli) - Ammontare',
 'Reddito da partecipazione (compresi nulli) - Ammontare',
 'Reddito da partecipazione  (comprensivo dei valori nulli) - Frequenza',
 'Reddito da partecipazione  (compresi nulli) - Frequenza',
 "Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Ammontare",
 'Reddito spettanza imprenditore ordinaria  (compresi nulli) - Ammontare',
 "Reddito di spettanza dell'imprenditore in contabilita' ordinaria  (comprensivo dei valori nulli) - Frequenza",
 'Reddito spettanza imprenditore ordinaria  (compresi nulli) - Frequenza',
 'Reddito spettanza imprenditore semplificata (compresi nulli) - Ammontare',
 "Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Ammontare",
 'Reddito spettanza imprenditore semplificata (compresi nulli) - Frequenza',
 "Reddito di spettanza dell'imprenditore in contabilita' semplificata (comprensivo dei valori nulli) - Frequenza",
 'Sigla Provincia_x',
 'Sigla Provincia_y',
 'Codice Istat_x',
 'Codice Istat_y',
 'Attesa VCT Fabbricati',
 'Attesa VCT Territorio',
 'Data Costituzione',
 'Denominazione Estera']

In [66]:
df_final.shape

(26799, 112)

In [67]:
df_final = df_final.drop(merged_to_drop, axis=1)

In [68]:
df_final.shape

(26799, 88)

### Cleanup Columns Names

In [69]:
new_columns = [c.replace(' - ', ' ') for c in  df_final.columns]

In [70]:
new_columns

['ANNO',
 'COMUNE_CAT_COD',
 'SPESA_CCC_FC01A',
 'TOT_SPESA_CCC_FC01A',
 'SPESA_CCC_FC01B',
 'TOT_SPESA_CCC_FC01B',
 'SPESA_CCC_FC01C',
 'TOT_SPESA_CCC_FC01C',
 'SPESA_CCC_FC01D',
 'TOT_SPESA_CCC_FC01D',
 'SPESA_CCC_FC02U',
 'TOT_SPESA_CCC_FC02U',
 'SPESA_CCC_FC03U',
 'TOT_SPESA_CCC_FC03U',
 'SPESA_CCC_FC04A',
 'TOT_SPESA_CCC_FC04A',
 'SPESA_CCC_FC04B',
 'TOT_SPESA_CCC_FC04B',
 'SPESA_CCC_FC05A',
 'TOT_SPESA_CCC_FC05A',
 'SPESA_CCC_FC05B',
 'TOT_SPESA_CCC_FC05B',
 'SPESA_CCC_FC06A',
 'TOT_SPESA_CCC_FC06A',
 'SPESA_CCC_FC06B',
 'TOT_SPESA_CCC_FC06B',
 'SPESA_CCC_tot',
 'TOT_SPESA_CCC_tot',
 'Codice Nazionale',
 'Denominazione Italiana',
 'Codice Catastale',
 'Ufficio Catasto Terreni',
 'Ufficio Catasto Fabbricati',
 'Codice Conservatoria',
 'Addizionale comunale dovuta Ammontare',
 'Addizionale comunale dovuta Frequenza',
 'Addizionale regionale dovuta Ammontare',
 'Addizionale regionale dovuta Frequenza',
 'Anno di imposta',
 'Codice Istat Comune',
 'Codice Istat Regione',
 'Codice catastale',
 'Denominazione Comune',
 'Imposta netta Ammontare',
 'Imposta netta Frequenza',
 'Numero contribuenti',
 'Reddito complessivo da 0 a 10000 euro Ammontare',
 'Reddito complessivo da 0 a 10000 euro Frequenza',
 'Reddito complessivo da 10000 a 15000 euro Ammontare',
 'Reddito complessivo da 10000 a 15000 euro Frequenza',
 'Reddito complessivo da 15000 a 26000 euro Ammontare',
 'Reddito complessivo da 15000 a 26000 euro Frequenza',
 'Reddito complessivo da 26000 a 55000 euro Ammontare',
 'Reddito complessivo da 26000 a 55000 euro Frequenza',
 'Reddito complessivo da 55000 a 75000 euro Ammontare',
 'Reddito complessivo da 55000 a 75000 euro Frequenza',
 'Reddito complessivo da 75000 a 120000 euro Ammontare',
 'Reddito complessivo da 75000 a 120000 euro Frequenza',
 'Reddito complessivo minore di zero euro Ammontare',
 'Reddito complessivo minore di zero euro Frequenza',
 'Reddito complessivo minore o uguale a zero euro Ammontare',
 'Reddito complessivo minore o uguale a zero euro Frequenza',
 'Reddito complessivo oltre 120000 euro Ammontare',
 'Reddito complessivo oltre 120000 euro Frequenza',
 'Reddito da fabbricati Ammontare',
 'Reddito da fabbricati Frequenza',
 'Reddito da lavoro dipendente e assimilati Ammontare',
 'Reddito da lavoro dipendente e assimilati Frequenza',
 'Reddito da pensione Ammontare',
 'Reddito da pensione Frequenza',
 'Reddito imponibile Ammontare',
 'Reddito imponibile Frequenza',
 'Reddito imponibile addizionale Ammontare',
 'Reddito imponibile addizionale Frequenza',
 'Reddito imponibile addizionale IRPEF Ammontare',
 'Reddito imponibile addizionale IRPEF Frequenza',
 'Regione',
 'tot_contribuenti',
 'Reddito lavoro autonomo Ammontare',
 'Reddito lavoro autonomo Frequenza',
 'Reddito da partecipazione Ammontare',
 'Reddito da partecipazione Frequenza',
 'Reddito imprenditore ordinario Ammontare',
 'Reddito imprenditore ordinario Frequenza',
 'Reddito imprenditore semplificata Ammontare',
 'Reddito imprenditore semplificata Frequenza',
 'Provincia',
 'Cod Istat']

In [71]:
df_final.columns = new_columns

In [ ]:
#df_final= pd.read_csv('./data/opencivitas_spesa_storica_dati_irpef.csv')

### Standardize Names

In [72]:
regions = set(df_final.Regione)
regions

{'ABRUZZO',
 'Abruzzo',
 'BASILICATA',
 'Basilicata',
 'CALABRIA',
 'CAMPANIA',
 'Calabria',
 'Campania',
 'EMILIA-ROMAGNA',
 'Emilia Romagna',
 'LAZIO',
 'LIGURIA',
 'LOMBARDIA',
 'Lazio',
 'Liguria',
 'Lombardia',
 'MARCHE',
 'MOLISE',
 'Marche',
 'Molise',
 'PIEMONTE',
 'PUGLIA',
 'Piemonte',
 'Puglia',
 'TOSCANA',
 'Toscana',
 'UMBRIA',
 'Umbria',
 'VENETO',
 'Veneto',
 nan}

In [74]:
def normalize(v):
    if type(v) is str:
        return v.replace(' ', '-').upper()
    else:
        return ''

In [77]:
len(set([normalize(v) for v in regions]))

16

In [78]:
df_final['Regione'] = df_final.Regione.apply(normalize)

In [79]:
df_final.to_csv('./data/opencivitas_spesa_storica_dati_irpef.csv',index=False)